# ===========================================================================
# Project:   SevenFi
# Copyright: ©2010 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :all, :required => [:sproutcore, :"sproutcore/animation"]  
proxy "/7digital/search/artists", :to => "localhost:82"